/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './rebirth-storage.module';
import * as import2 from './rebirth-storage';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from '@angular/core/src/i18n/tokens';
class RebirthStorageModuleInjector extends import0.NgModuleInjector<import1.RebirthStorageModule> {
  _RebirthStorageModule_0:import1.RebirthStorageModule;
  __StorageService_1:import2.StorageService;
  __LOCALE_ID_2:any;
  __TRANSLATIONS_FORMAT_3:any;
  constructor(parent:import3.Injector) {
    super(parent,[],[]);
  }
  get _StorageService_1():import2.StorageService {
    if ((this.__StorageService_1 == (null as any))) { (this.__StorageService_1 = new import2.StorageService()); }
    return this.__StorageService_1;
  }
  get _LOCALE_ID_2():any {
    if ((this.__LOCALE_ID_2 == (null as any))) { (this.__LOCALE_ID_2 = (null as any)); }
    return this.__LOCALE_ID_2;
  }
  get _TRANSLATIONS_FORMAT_3():any {
    if ((this.__TRANSLATIONS_FORMAT_3 == (null as any))) { (this.__TRANSLATIONS_FORMAT_3 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_3;
  }
  createInternal():import1.RebirthStorageModule {
    this._RebirthStorageModule_0 = new import1.RebirthStorageModule();
    return this._RebirthStorageModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.RebirthStorageModule)) { return this._RebirthStorageModule_0; }
    if ((token === import2.StorageService)) { return this._StorageService_1; }
    if ((token === import4.LOCALE_ID)) { return this._LOCALE_ID_2; }
    if ((token === import4.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const RebirthStorageModuleNgFactory:import0.NgModuleFactory<import1.RebirthStorageModule> = new import0.NgModuleFactory(RebirthStorageModuleInjector,import1.RebirthStorageModule);